### ISSUE TITLE
Default RobotoFlex not appearing

### ISSUE THREAD

**Issue by dberlow** [Lorp/ParaSync#3]

**Comment by dberlow** [comment]
Nice work on this!

**Comment by Lorp** [comment]
This seems to be fixed now, although RobotoFlex still

**Comment by Lorp** [comment]
This seems to be issue #1. The commit 2b408fc67acad79f6eb320fc03bd4f01828de5ec should have fixed the issue. In RobotoFlex’s case it now forces all samples to opsz 14 (because that’s RobotoFlex’s default opsz), whatever the size in px of the sample.

However RobotoFlex is still out of sync with the other fonts. For example, set XOPQ to 156, XTRA to 390 – which are both within the axis ranges of Amstelvar and RobotoFlex. You’ll observe that RobotoFlex H, specifically the transparent gap between the vertical stems, is clearly narrower than the same gap in Amstelvar and the other fonts.

**Comment by Lorp** [comment]
Note that ParaSync _ignores_ the font’s axis defaults for the parametric axes in the UI (because the whole point is to set all fonts to identical values). By contrast it sets axes _not_ in the UI to default, and they are not controllable in ParaSync.

**Comment by Lorp** [comment]
I’m seeing odd XTRA calibration in all the versions of RobotoFlex that I have, with the H glyph consistently too narrow. The following images show RobotoFlex compared with Amstelvar, with XTRA=500 and all user axes at default: first in ParaSync, then in Axis-Praxis. On my understanding, Amstelvar is correct.

![Screenshot 2024-10-24 at 12 43 12](https://github.com/user-attachments/assets/5fbecb89-a98d-477e-8306-227639c56a32)

![Screenshot 2024-10-24 at 12 41 33](https://github.com/user-attachments/assets/0047e999-ce8d-488a-8ded-d50bb69d03f2)

**Comment by Lorp** [comment]
The drag-drop issue #4 is now fixed, so if you can try an up-to-date parametric RobotoFlex, that would be great.

**Comment by Lorp** [comment]
Raised an issue about the RobotoFlex XTRA calibration here https://github.com/googlefonts/roboto-flex-avar2/issues/64

**Comment by Lorp** [comment]
Not a ParaSync issue. Follow up about XTRA definition in the RobotoFlex issue above.
